"""Increase password_hash field size

Revision ID: 12559d530392
Revises: ce070c8538d1
Create Date: 2025-11-29 14:53:33.367667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12559d530392'
down_revision = 'ce070c8538d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
